#uses the the default terminal colour
set-option -sa terminal-overrides ",xterm*:Tc"

#Enables mouse support
set -g mouse on

#set the prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

#Sets the starting index of windows and panes to 1 (instead of 0)
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

#Opens new panes in the current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

#plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'

set -g status-position top
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session

run '~/.tmux/plugins/tpm/tpm'
